export const blockedAttr = [
    'Pitboss',
    'Douglas Degen',
    'Bean',
    'BigBrain',
    'Puzz',
    'Custom',
    'Rageki',
    'Devonair',
    'Gecko',
    'PonyBoy',
    'Silver',
    'Bronze',
    'Slow AF',
    'Nemov',
    'Rocketeer',

    'Teslerr Model J',
    'Toasty',
    'Kachow',
    'Souls',
    'Coug',
    'DatWank',
    'Legend',
    'Starbase',
    'Dexter',
    'Umbra Waifu',

    'Cheemz',
    'CO2',
    'Dersmut',
    'Kneecap',
    'Ramen',
    'Tuxkuro',
    'Norrin',
    'Oilio',
    'Cazzual',
    'Afib'
];

export const allowedModels = ['BW', 'BWTSLR'];
